[package]
name = "winmsg"
version = "0.1.0"
edition = "2021"

[dependencies]
bitfield = "0.17.0"

[dependencies.winapi]
version = "0.3.9"
features = [
    "winuser",
    "windef",
    "minwindef",
    "impl-default"
]